//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_ETC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasRealizadas
    {
        public int idVenta { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<int> idcomprador { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
